name: Build-status

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    name: "uxxxx0/hw0"
    runs-on: ubuntu-latest
    container: pratikvn/ubuntu-ginkgo-develop
    
    steps:
    - uses: actions/checkout@v2
    - name: info
      run: |
        g++ -v
        cmake --version
    - name: build 
      run: |
        echo $Ginkgo_DIR
        mkdir build
        cd build/
        cmake -DCMAKE_PREFIX_PATH=${HOME}/install -DNLA4HPC_HW=0 ..
        make -j10
        ctest -V
